# Generated by Django 4.2.26 on 2026-02-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.CharField(
                choices=[("up", "Helpful"), ("down", "Not helpful")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant")], max_length=10
            ),
        ),
    ]
