# Generated by Django 4.2.26 on 2026-04-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_feedback_rating_alter_message_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatIpQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(db_index=True, max_length=45, unique=True)),
                ("successful_replies", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
