# Generated by Django 4.2.26 on 2026-04-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chat_ip_quota"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatIpReplyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(db_index=True, max_length=45)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ChatIpQuota",
        ),
        migrations.AddIndex(
            model_name="chatipreplylog",
            index=models.Index(
                fields=["ip", "created_at"], name="chat_chatip_ip_e26b6a_idx"
            ),
        ),
    ]
