<<<<<<< HEAD
def find_agents_by_county(county: str, dataframe: pd.DataFrame) -> list[dict]:
    """
    Returns all agents matching the given county (case-insensitive).
    If multiple agents share a county, they are sorted by Score descending
    so the best-matched agent is first.
    """
    county_clean = county.strip().lower()
    matches = dataframe[dataframe['County'].str.strip().str.lower() == county_clean].copy()
=======
import smtplib
import pandas as pd
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# -------------------------------------------------------
# CONFIG — move these to environment variables before pushing to GitHub
# -------------------------------------------------------
GMAIL_ADDRESS      = 'you@gmail.com'
GMAIL_APP_PASSWORD = 'abcd efgh ijkl mnop'  # myaccount.google.com/apppasswords
FROM_NAME          = 'Website Chatbot'

# -------------------------------------------------------
# LOAD AGENTS CSV
# -------------------------------------------------------
df = pd.read_csv('agents.csv')
df.columns = df.columns.str.strip()


# -------------------------------------------------------
# AGENT LOOKUP
# -------------------------------------------------------
def find_agents_by_county(county: str) -> list[dict]:
    """
    Returns all agents for a given county, sorted by Score descending.
    """
    county_clean = county.strip().lower()
    matches = df[df['County'].str.strip().str.lower() == county_clean].copy()
>>>>>>> 8a0c248ac08894b32a3dba5040cb7bfe7d813a86

    if matches.empty:
        return []

    if 'Score' in matches.columns:
        matches = matches.sort_values('Score', ascending=False)

    return matches[['Name', 'Title', 'Specialty', 'County', 'Email', 'Phone']].to_dict(orient='records')


<<<<<<< HEAD
# --- Quick test ---
test_county = df['County'].iloc[0]   # Uses first county in your CSV as a test
results = find_agents_by_county(test_county, df)
print(f"Test lookup for '{test_county}': {len(results)} agent(s) found")
for r in results:
    print(f"  → {r['Name']} | {r['Email']} | {r['Phone']}")

def build_email_html(user_name: str, user_email: str, user_message: str, chat_log: list[dict]) -> str:
    """
    Builds a clean HTML email body.
    chat_log = list of {role: 'user'|'assistant', content: 'text'}
    """
=======
# -------------------------------------------------------
# EMAIL TEMPLATE
# -------------------------------------------------------
def _build_email_html(user_name: str, user_email: str, user_message: str, chat_log: list[dict]) -> str:
>>>>>>> 8a0c248ac08894b32a3dba5040cb7bfe7d813a86
    chat_rows = ''
    for msg in chat_log:
        role = msg.get('role', 'unknown').capitalize()
        content = msg.get('content', '').replace('<', '&lt;').replace('>', '&gt;')
        bg = '#f0f4ff' if role == 'User' else '#f9f9f9'
        chat_rows += f"""
        <tr style='background:{bg};'>
            <td style='padding:8px 12px; width:80px; font-weight:bold; color:#555;'>{role}</td>
            <td style='padding:8px 12px; color:#333;'>{content}</td>
<<<<<<< HEAD
        </tr>
        """

    return f"""
    <html><body style='font-family:Arial,sans-serif; color:#333; max-width:680px; margin:auto;'>
        <h2 style='color:#2c5f9e;'> New Chat Escalation Request</h2>
        <p>A website visitor was unable to find the answer they needed and has requested to be contacted.</p>

=======
        </tr>"""

    return f"""
    <html><body style='font-family:Arial,sans-serif; color:#333; max-width:680px; margin:auto;'>
        <h2 style='color:#2c5f9e;'>📩 New Chat Escalation</h2>
        <p>A visitor could not find the answer they needed and has requested to be contacted.</p>
>>>>>>> 8a0c248ac08894b32a3dba5040cb7bfe7d813a86
        <table style='width:100%; border-collapse:collapse; margin-bottom:24px;'>
            <tr><td style='padding:6px; font-weight:bold; width:140px;'>Name:</td><td style='padding:6px;'>{user_name}</td></tr>
            <tr><td style='padding:6px; font-weight:bold;'>Email:</td><td style='padding:6px;'><a href='mailto:{user_email}'>{user_email}</a></td></tr>
            <tr><td style='padding:6px; font-weight:bold;'>Question:</td><td style='padding:6px;'>{user_message}</td></tr>
        </table>
<<<<<<< HEAD

        <h3 style='color:#2c5f9e;'> Full Chat History</h3>
        <table style='width:100%; border-collapse:collapse; border:1px solid #ddd;'>
            {chat_rows}
        </table>

        <p style='margin-top:24px; font-size:12px; color:#999;'>This email was automatically generated by the website chatbot escalation system.</p>
    </body></html>
    """

print('Email template function ready')

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def send_escalation_email(to_email: str, agent_name: str, user_name: str,
                           user_email: str, user_message: str, chat_log: list[dict]) -> dict:
    """
    Sends the escalation email to the matched agent via Gmail SMTP.
    Returns {success: bool, message: str}
    """
    try:
        html_content = build_email_html(user_name, user_email, user_message, chat_log)

        msg = MIMEMultipart('alternative')
        msg['Subject'] = f'Chat Escalation from {user_name} — needs follow-up'
        msg['From']    = f'{FROM_NAME} <{GMAIL_ADDRESS}>'
        msg['To']      = to_email
        # Optional: reply-to goes directly to the user
        msg.add_header('Reply-To', user_email)

        msg.attach(MIMEText(html_content, 'html'))

        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_ADDRESS, to_email, msg.as_string())

        return {'success': True, 'message': f'Email sent to {agent_name} ({to_email})'}

    except smtplib.SMTPAuthenticationError:
        return {'success': False, 'message': 'Gmail authentication failed. Check your App Password.'}
    except Exception as e:
        return {'success': False, 'message': str(e)}

print(' Gmail SMTP send function ready')

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import uvicorn
import nest_asyncio

nest_asyncio.apply()

app = FastAPI(title='Chatbot Escalation API')

# Allow requests from your chatbot frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=['*'],   # 🔒 Restrict to your domain in production
    allow_methods=['*'],
    allow_headers=['*'],
)


# --- Request / Response Models ---

class ChatMessage(BaseModel):
    role: str       # 'user' or 'assistant'
    content: str

class EscalationRequest(BaseModel):
    county: str
    user_name: str
    user_email: str
    user_message: str          # The unanswered question
    chat_log: list[ChatMessage]
    preferred_agent_email: Optional[str] = None  # Optional: if user picks a specific agent


# --- Endpoints ---

@app.get('/health')
def health():
    return {'status': 'ok'}


@app.get('/agents')
def get_agents(county: str):
    """
    Returns list of agents for a given county.
    Called by the frontend to populate the contact cards.
    """
    agents = find_agents_by_county(county, df)
    if not agents:
        raise HTTPException(status_code=404, detail=f'No agents found for county: {county}')
    return {'county': county, 'agents': agents}


@app.post('/escalate')
def escalate(req: EscalationRequest):
    """
    Sends escalation email to the best-matched agent for the user's county,
    including the full chat log.
    """
    agents = find_agents_by_county(req.county, df)

    if not agents:
        raise HTTPException(status_code=404, detail=f'No agents found for county: {req.county}')

    # Use preferred agent if specified, otherwise use top-scored agent
    if req.preferred_agent_email:
        agent = next((a for a in agents if a['Email'] == req.preferred_agent_email), agents[0])
    else:
        agent = agents[0]

    result = send_escalation_email(
        to_email=agent['Email'],
        agent_name=agent['Name'],
        user_name=req.user_name,
        user_email=req.user_email,
        user_message=req.user_message,
        chat_log=[m.dict() for m in req.chat_log]
    )

    if not result['success']:
        raise HTTPException(status_code=500, detail=result['message'])

    return {
        'success': True,
        'message': f"Your message has been sent to {agent['Name']}. They will contact you at {req.user_email}.",
        'agent': agent
    }


print(' FastAPI app defined — run the next cell to start the server')
=======
        <h3 style='color:#2c5f9e;'>💬 Full Chat History</h3>
        <table style='width:100%; border-collapse:collapse; border:1px solid #ddd;'>
            {chat_rows}
        </table>
        <p style='margin-top:24px; font-size:12px; color:#999;'>Sent automatically by the website chatbot.</p>
    </body></html>"""


# -------------------------------------------------------
# SEND ESCALATION EMAIL
# -------------------------------------------------------
def send_escalation_email(
    county: str,
    user_name: str,
    user_email: str,
    user_message: str,
    chat_log: list[dict],
    preferred_agent_email: str = None
) -> dict:
    """
    Call this directly from your existing chatbot message handler
    when the user triggers escalation.

    Returns {'success': True/False, 'message': str, 'agent': dict}

    Example usage inside your OpenAI message handler:
        result = send_escalation_email(
            county=detected_county,
            user_name=user_name,
            user_email=user_email,
            user_message=last_user_message,
            chat_log=conversation_history,   # your existing OpenAI messages list
        )
        if result['success']:
            reply = f"I've sent your details to {result['agent']['Name']}. They'll be in touch at {user_email}."
        else:
            reply = "Sorry, something went wrong sending your message. Please try again."
    """
    agents = find_agents_by_county(county)

    if not agents:
        return {'success': False, 'message': f'No agents found for county: {county}', 'agent': None}

    # Use preferred agent if the user picked one, otherwise use top-scored
    if preferred_agent_email:
        agent = next((a for a in agents if a['Email'] == preferred_agent_email), agents[0])
    else:
        agent = agents[0]

    try:
        html = _build_email_html(user_name, user_email, user_message, chat_log)

        msg = MIMEMultipart('alternative')
        msg['Subject'] = f'Chat Escalation from {user_name}'
        msg['From']    = f'{FROM_NAME} <{GMAIL_ADDRESS}>'
        msg['To']      = agent['Email']
        msg.add_header('Reply-To', user_email)  # Agent hits reply → goes to user
        msg.attach(MIMEText(html, 'html'))

        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_ADDRESS, agent['Email'], msg.as_string())

        return {
            'success': True,
            'message': f"Email sent to {agent['Name']} ({agent['Email']})",
            'agent': agent
        }

    except smtplib.SMTPAuthenticationError:
        return {'success': False, 'message': 'Gmail authentication failed. Check your App Password.', 'agent': None}
    except Exception as e:
        return {'success': False, 'message': str(e), 'agent': None}
>>>>>>> 8a0c248ac08894b32a3dba5040cb7bfe7d813a86
